# Generated by Django 3.0.4 on 2020-04-04 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200405_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calibration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='dummy_item_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_serial_num',
            field=models.CharField(default='dummy_item_serial_num', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Ground', 'Ground')], default='Flight', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('Location1', 'Location1'), ('Location2', 'Location2')], default='Location1', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_num',
            field=models.CharField(default='dummy_model_num', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='project_name',
            field=models.CharField(default='dummry_project_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='dummy_slug'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
