# Generated by Django 3.0.4 on 2020-04-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200405_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calibration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_serial_num',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Ground', 'Ground')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('Location1', 'Location1'), ('Location2', 'Location2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='model_num',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
