# Generated by Django 3.0.4 on 2020-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_greeting_latest_stats_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(default='')),
                ('added_ts', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(choices=[('Location1', 'Location1'), ('Location2', 'Location2')], max_length=50)),
                ('item_type', models.CharField(choices=[('Flight', 'Flight'), ('Ground', 'Ground')], max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('model_num', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('item_serial_num', models.CharField(max_length=255)),
                ('calibration_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
